; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=wasm32-unknown-unknown -mattr=+reference-types < %s | FileCheck %s

!0 = !{!"externref"}
!1 = !{!"funcref"}
!wasm.type_info = !{!0, !1}

%wasmref = type ptr addrspace(256)
%externref = type ptr addrspace(257)
%funcref = type ptr addrspace(258)
declare %wasmref @llvm.wasm.ref.null(i32) nounwind
declare i32 @llvm.wasm.ref.is_null(%wasmref) nounwind

define %externref @get_null_extern() {
; CHECK-LABEL: get_null_extern:
; CHECK:         .functype get_null_extern () -> (externref)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    ref.null_extern
; CHECK-NEXT:    # fallthrough-return
  %null_untyped = call %wasmref @llvm.wasm.ref.null(i32 0)
  %null = addrspacecast %wasmref %null_untyped to %externref
  ret %externref %null
}

define %funcref @get_null_func() {
; CHECK-LABEL: get_null_func:
; CHECK:         .functype get_null_func () -> (funcref)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    ref.null_func
; CHECK-NEXT:    # fallthrough-return
  %null_untyped = call %wasmref @llvm.wasm.ref.null(i32 1)
  %null = addrspacecast %wasmref %null_untyped to %funcref
  ret %funcref %null
}

define i32 @ref_is_null_extern(%externref %eref) {
; CHECK-LABEL: ref_is_null_extern:
; CHECK:         .functype ref_is_null_extern (externref) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    ref.null_extern
; CHECK-NEXT:    ref.is_null
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    ref.is_null
; CHECK-NEXT:    i32.add
; CHECK-NEXT:    # fallthrough-return
  %null_untyped = call %wasmref @llvm.wasm.ref.null(i32 0)
  %is_null = call i32 @llvm.wasm.ref.is_null(%wasmref %null_untyped)
  %eref_untyped = addrspacecast %externref %eref to %wasmref
  %arg_is_null = call i32 @llvm.wasm.ref.is_null(%wasmref %eref_untyped)
  %res = add i32 %is_null, %arg_is_null
  ret i32 %res
}

define i32 @ref_is_null_func(%funcref %fref) {
; CHECK-LABEL: ref_is_null_func:
; CHECK:         .functype ref_is_null_func (funcref) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    ref.null_func
; CHECK-NEXT:    ref.is_null
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    ref.is_null
; CHECK-NEXT:    i32.add
; CHECK-NEXT:    # fallthrough-return
  %null_untyped = call %wasmref @llvm.wasm.ref.null(i32 1)
  %is_null = call i32 @llvm.wasm.ref.is_null(%wasmref %null_untyped)
  %fref_untyped = addrspacecast %funcref %fref to %wasmref
  %arg_is_null = call i32 @llvm.wasm.ref.is_null(%wasmref %fref_untyped)
  %res = add i32 %is_null, %arg_is_null
  ret i32 %res
}
